/**
 * Render a topic's numbered sources into its `data/SOURCES.md`:
 *
 *   pnpm tsx scripts/sources-md.ts <topic-slug>
 *
 * Reads `src/content/topics/<slug>/data/sources.json` (validated with the
 * shared schema, src/content/schema/sources.ts) and writes one line per
 * source, `- [S1] English text / 中文 — https://…`, plus the note when there
 * is one. Only the block between the two marker comments is replaced, so the
 * rest of SOURCES.md (map data provenance, licences, registration notes) is
 * kept; without markers the block is appended. Exit 1 on invalid input.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sourcesFile, type SourceEntry } from '../src/content/schema/sources';
import { formatIssues } from '../src/engines/schemas';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOPICS_DIR = process.env.ATLAS_TOPICS_DIR ? resolve(process.env.ATLAS_TOPICS_DIR) : join(ROOT, 'src/content/topics');

export const BEGIN = '<!-- sources:begin (generated by scripts/sources-md.ts from sources.json; edit sources.json) -->';
export const END = '<!-- sources:end -->';

/** One Markdown list line per source. */
export function sourceLine(s: SourceEntry): string {
  const text = s.text.zh ? `${s.text.en} / ${s.text.zh}` : s.text.en;
  const note = s.note ? ` (${s.note.zh ? `${s.note.en} / ${s.note.zh}` : s.note.en})` : '';
  return `- [${s.id}] ${text}${note}${s.url ? ` — ${s.url}` : ''}`;
}

/** The generated block, markers included. */
export function sourcesBlock(sources: readonly SourceEntry[]): string {
  return [BEGIN, ...sources.map(sourceLine), END].join('\n');
}

/** `existing` with its generated block replaced (or a new file / appended block). */
export function mergeSourcesMd(existing: string | null, block: string, topic: string): string {
  if (existing === null) return `# Sources · ${topic}\n\n${block}\n`;
  const start = existing.indexOf(BEGIN);
  const end = existing.indexOf(END);
  if (start >= 0 && end > start) return existing.slice(0, start) + block + existing.slice(end + END.length);
  return `${existing.replace(/\s*$/, '')}\n\n## Numbered sources\n\n${block}\n`;
}

function main(): void {
  const slug = process.argv[2];
  if (!slug) {
    console.error('usage: pnpm tsx scripts/sources-md.ts <topic-slug>');
    process.exitCode = 1;
    return;
  }
  const dataDir = join(TOPICS_DIR, slug, 'data');
  const input = join(dataDir, 'sources.json');
  if (!existsSync(input)) {
    console.error(`sources-md: ${relative(ROOT, input)} not found`);
    process.exitCode = 1;
    return;
  }
  const parsed = sourcesFile.safeParse(JSON.parse(readFileSync(input, 'utf8')));
  if (!parsed.success) {
    console.error(`sources-md: invalid ${relative(ROOT, input)}\n  ${formatIssues(parsed.error).join('\n  ')}`);
    process.exitCode = 1;
    return;
  }
  const output = join(dataDir, 'SOURCES.md');
  const existing = existsSync(output) ? readFileSync(output, 'utf8') : null;
  writeFileSync(output, mergeSourcesMd(existing, sourcesBlock(parsed.data.sources), slug));
  console.log(`sources-md: ${parsed.data.sources.length} source(s) -> ${relative(ROOT, output)}`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
